import Collection from "@/components/blocks/Collection";
import FeaturedCollection from "@/components/blocks/FeaturedCollection";
import Hero from "@/components/blocks/Hero";
import IconTitleText from "@/components/blocks/IconTitleText";
import CtaSec from "@/components/blocks/CtaSec";
import Head from "next/head";
import ArtCategory from "@/components/blocks/ArtCategory";

export default function Home() {
  return (
    <>
      <Head>
        <title>NFTERS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <IconTitleText />
        <Collection />
        <FeaturedCollection />
        <CtaSec />
        <ArtCategory />
      </main>
    </>
  );
}
